#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
#  J.A.R.V.I.S. — macOS Installer
#  Usage: chmod +x install.sh && ./install.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "======================================================"
echo "  J.A.R.V.I.S. — Installer"
echo "======================================================"
echo ""

# 1. Verify macOS ──────────────────────────────────────────────────────────────
if [[ "$(uname)" != "Darwin" ]]; then
    echo "ERROR: JARVIS requires macOS."
    exit 1
fi

# 2. Find python3 and verify >= 3.9 ───────────────────────────────────────────
PYTHON=$(which python3 2>/dev/null) || {
    echo "ERROR: python3 not found."
    echo "  Install it from https://python.org or via Homebrew: brew install python"
    exit 1
}

PY_VERSION=$("$PYTHON" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$(echo "$PY_VERSION" | cut -d. -f1)
PY_MINOR=$(echo "$PY_VERSION" | cut -d. -f2)

if [[ "$PY_MAJOR" -lt 3 ]] || { [[ "$PY_MAJOR" -eq 3 ]] && [[ "$PY_MINOR" -lt 9 ]]; }; then
    echo "ERROR: Python 3.9+ required. Found Python $PY_VERSION."
    echo "  Install a newer version from https://python.org"
    exit 1
fi

echo "  Python $PY_VERSION ......................... OK"

# 3. Create virtual environment (.venv/) ──────────────────────────────────────
if [[ -d "$SCRIPT_DIR/.venv" ]]; then
    echo "  Virtual environment already exists, skipping creation."
else
    "$PYTHON" -m venv "$SCRIPT_DIR/.venv"
    echo "  Virtual environment created ........... OK"
fi

# 4. Install Python dependencies ──────────────────────────────────────────────
echo "  Installing dependencies (this may take a moment)..."
"$SCRIPT_DIR/.venv/bin/pip" install -q --upgrade pip
"$SCRIPT_DIR/.venv/bin/pip" install -q -r "$SCRIPT_DIR/requirements.txt"
echo "  Dependencies installed ................ OK"

# 5. Check for claude CLI (non-blocking warning) ───────────────────────────────
if command -v claude &>/dev/null; then
    echo "  Claude Code CLI ....................... OK"
else
    echo ""
    echo "  WARNING: 'claude' CLI not found."
    echo "  JARVIS will open Terminal but the 'claude' command will fail inside it."
    echo "  Install Claude Code: https://claude.ai/code"
    echo ""
fi

# 6. Make main script executable ──────────────────────────────────────────────
chmod +x "$SCRIPT_DIR/bienvenido_jarvis.py"

# 7. Write jarvis.sh launcher ─────────────────────────────────────────────────
cat > "$SCRIPT_DIR/jarvis.sh" <<LAUNCHER
#!/bin/bash
# J.A.R.V.I.S. launcher — generated by install.sh
source "$SCRIPT_DIR/.venv/bin/activate"
exec python "$SCRIPT_DIR/bienvenido_jarvis.py" "\$@"
LAUNCHER
chmod +x "$SCRIPT_DIR/jarvis.sh"
echo "  Launcher (jarvis.sh) created .......... OK"

# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "======================================================"
echo "  Installation complete!"
echo ""
echo "  To run JARVIS:"
echo "    ./jarvis.sh"
echo ""
echo "  IMPORTANT: When macOS asks for microphone access,"
echo "  click Allow — JARVIS needs it to hear your claps."
echo "======================================================"
